version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "@storybook/*"
      - dependency-name: "storybook"
    ignore:
      - dependency-name: "@storybook/*"
        update-types:
        - version-update:semver-patch
    groups:
      storybook-addons:
        patterns:
          - "@storybook/addon-*"
    open-pull-requests-limit: 20
