name: Deploy Production
on:
  push:
    branches: [master]
    paths:
      - .github/workflows/deploy-production.yml
      - public/**
      - src/**
      - index.html
      - vite.config.ts
      - pnpm-lock.yaml
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: 'node_modules'
          key: deps-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            deps-
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build site
        env:
          NODE_ENV: production
          VITE_SEGMENT_KEY: ${{ secrets.PRODUCTION_SEGMENT_KEY }}
          VITE_SEGMENT_HOST: ${{ secrets.PRODUCTION_SEGMENT_HOST }}
          VITE_SENTRY_DSN: ${{ secrets.PRODUCTION_SENTRY_DSN }}
          VITE_SENTRY_HOST: ${{ secrets.PRODUCTION_SENTRY_HOST }}
          VITE_STATSIG_KEY: ${{ secrets.PRODUCTION_STATSIG_KEY }}
        run: pnpm build
      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.PRODUCTION_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PRODUCTION_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.PRODUCTION_AWS_REGION }}
        run: |
          aws s3 sync build s3://${{ secrets.PRODUCTION_AWS_S3_BUCKET }} \
            --exclude '*.html' \
            --cache-control max-age=31536000
          aws s3 sync build s3://${{ secrets.PRODUCTION_AWS_S3_BUCKET }} \
            --exclude '*' --include '*.html'
      - name: Invalidate cloudfront cache
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.PRODUCTION_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PRODUCTION_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.PRODUCTION_AWS_REGION }}
        run: aws cloudfront create-invalidation
          --distribution-id ${{ secrets.PRODUCTION_AWS_CLOUDFRONT_DISTRIBUTION }}
          --paths '/index.html'
