name: RelativeCI
on:
  push:
    branches: [master]
    paths:
      - .github/workflows/relative.yml
      - public/**
      - src/**
      - index.html
      - vite.config.ts
      - yarn.lock
  pull_request:
    branches: [master]
    paths:
      - .github/workflows/relative.yml
      - public/**
      - src/**
      - index.html
      - vite.config.ts
      - yarn.lock
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name == 'push' && github.run_number }}
  cancel-in-progress: true
jobs:
  relative:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache dependencies
        uses: actions/cache@v2
        id: cache
        with:
          path: '**/node_modules'
          key: deps-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            deps-
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build stats
        run: yarn build-stats
      - name: RelativeCI
        uses: relative-ci/agent-action@v2
        with:
          webpackStatsFile: build/webpack-stats.json
          token: ${{ secrets.GITHUB_TOKEN }}
          key: ${{ secrets.RELATIVE_CI_KEY }}
